version: '2'

services:
  php:
#    image: 'php:7.2-apache-buster'
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: 'mysql:5.7.25'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'hrm'
      MYSQL_PASSWORD: 'root'
    ports:
      - '33006:3306'

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: 'user'
      PMA_PASSWORD: 'root'
      UPLOAD_LIMIT: 1G

  node:
    image: 'node:8.10'
    volumes:
      - ./:/var/www/html

  mailhog:
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
